name: Automation Test Suite

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Poin Penilaian: Manual Trigger

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Jalankan API Test (Gunakan Secret untuk APP_ID agar aman)
      - name: Run API Tests
        run: ./gradlew apiTest -DAPP_ID=${{ secrets.APP_ID }}
        continue-on-error: true

      # Jalankan Web Test
      - name: Run Web UI Tests
        run: ./gradlew webTest
        continue-on-error: true

      # Simpan Report sebagai Artifact agar bisa didownload (Poin Penilaian 5)
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cucumber-reports
          path: build/reports/cucumber/